# Generated by Django 5.0.6 on 2024-05-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('NGO/GOVT', 'NGO/GOVT'), ('HANDLER', 'HANDLER'), ('RECIPIENT', 'RECIPIENT')], max_length=50)),
                ('ethAddress', models.CharField(blank=True, max_length=42, null=True, unique=True)),
            ],
        ),
    ]
