# Generated by Django 5.0.6 on 2024-05-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLedgerMainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethAddress', models.CharField(max_length=42, unique=True)),
                ('acctName', models.CharField(max_length=60)),
                ('userType', models.CharField(choices=[('NGO/GOVT', 'NGO/GOVT'), ('HANDLER', 'HANDLER'), ('RECIPIENT', 'RECIPIENT')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
