# Generated by Django 5.0.6 on 2024-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidLedgerMainApp', '0003_customuser_delete_accountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image', models.ImageField(upload_to='qr_codes')),
            ],
        ),
    ]
